version: 1.0.{build}
os: Visual Studio 2017
platform: x64
clone_folder: C:\projects\auvlib
#shallow_clone: true
branches:
  only:
    - master
environment:
  matrix:
  - CONFIG: Release
    BOOST_ROOT: C:/Libraries/boost_1_65_1
    OpenCV_DIR: C:/tools/opencv/build/x64/vc14/lib
    PYTHON: 27
install:
  - cd C:\projects\auvlib
  - git submodule update --init 
  #- cinst python2 appveyor already has python
  - cinst OpenCV --version 3.4.7
build:
  parallel: true
build_script:
  # Tutorials and tests
  #- set PATH=C:\Python%PYTHON%-x64;C:\Python%PYTHON%-x64\Scripts;%PATH%
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=%CONFIG%
      -G "Visual Studio 15 2017 Win64"
      -DAUVLIB_WITH_GSF=OFF
      -DAUVLIB_USE_LIBIGL_GLFW=ON
      -DAUVLIB_USE_LIBIGL_TINYXML=ON
      -DAUVLIB_EXPORT_BUILD=OFF
      -DCMAKE_SKIP_INSTALL_RULES=true
      ../
      #-DCMAKE_INSTALL_PREFIX=../install
  - set MSBuildLogger="C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - set MSBuildOptions=/v:m /m /p:BuildInParallel=true /p:Configuration=%CONFIG% /logger:%MSBuildLogger%
  #- msbuild %MSBuildOptions% INSTALL.vcxproj
  - msbuild %MSBuildOptions% ALL_BUILD.vcxproj
